title: Home
headerStyle: boxed
quicklaunch:
  searchDescriptions: true
disableCollapse: true
useEqualHeights: true
fiveColumns: true
layout:
  Bookmarks:
    style: row
    columns: 4
  widgets:
    icon: mdi-widgets
    style: row
    columns: 3
    tab: Main
  mediarr:
    icon: mdi-projector
    style: row
    columns: 3
    tab: Main
  self-hosted:
    icon: mdi-devices
    style: row
    columns: 3
    tab: Main
  monitoring:
    icon: mdi-glasses
    style: row
    columns: 3
    tab: Admin
  hosts:
    icon: mdi-wan
    style: row
    columns: 3
    tab: Admin
  documents:
    icon: mdi-file-document
    style: row
    columns: 4
    tab: Admin
  data:
    icon: mdi-sitemap
    style: row
    columns: 3
    tab: Common
  banking:
    icon: mdi-credit-card
    style: row
    columns: 4
    tab: Common
  house:
    icon: mdi-home-search
    style: row
    columns: 4
    tab: Common
  health:
    icon: mdi-heart-pulse
    style: row
    columns: 4
    tab: Common
  mediarr-files:
    icon: mdi-projector
    style: row
    columns: 4
    tab: Common