apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secrets
    namespace: storage
stringData:
    #ENC[AES256_GCM,data:OOxweme1Vu0=,iv:i0n259uG47ZR30t2Xwg3/mS68QgHFQd/+VoL6W8qXkA=,tag:dvtOUAzHgtOwoAW4zZgmhQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:0Y51Ew==,iv:TZ69QnYrxnP1HygtTSPBlqFVcEbShU/vALasp9dP/rc=,tag:h7Dub4Byev+xNZGhLd5oxQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:sefJdogLQ1RNFA==,iv:f2PNnSRZsinr9O4t0xJmq47v86hkcpnC6u7SPq8NrLM=,tag:C0b0XAD/eoaylmOR6RhwFw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lQj+Wrr++IrKaz61nXS/J5te3gc=,iv:q2cI8JJgKc0BDDoFLMsUoW4Amr0hZXNqzeMoOJ2aLV4=,tag:Jjp5uH2IUUE0pY+OTERN9Q==,type:str]
sops:
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aFZQbkRJeGpqUklGVGcw
            Z1p5MCtqWFZibzFyYnc0dWx1cHZGZGZaLzF3CjlLdmN0cGZ3Y1kzeGxpekl3STJQ
            bFhxcTlSeVF2dnI5QTlCVnJLWEVHZjAKLS0tIDR2UVJSc3BZVHdNWitPVzVNWWZC
            b2R1SHpyUEVvUkQ5VDI4WjBwandJdFEKAo4FwoQbT92B0OwJGzS0s+9VOh1D1yQE
            rs4X+O7gL9bqFg8Yj+b0lKn9ONb4p87Kxf/kZ1KwT7+IP93jbE6fMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T23:04:54Z"
    mac: ENC[AES256_GCM,data:u+Qayv7GSBUPL+ySGbEwK02/B56lkF7nYFW7yzpjbfVyNQ/dCCXd3blSFhlvNtwKNc7nwd0hnvy9sm/cyt5eLj2r5N28wkB7iuldf2kPO1GtBysigczToSLgKCtyqah+0RIifoiw36L7bKmGN0TQKjx3gkU8M0PmH2I2NqaZRe0=,iv:E6Tf5NIRD+6+zXq33Uf9uQ95r8fCLt8AWj5iRkeTjTc=,tag:3t67PnRbCI0nIDGY7Oi/BQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
