---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gphotos
  namespace: &ns dev
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            enabled: true
            image:
              repository: ghcr.io/davidecavestro/gphotos-cdp
              tag: 1.3.1
              pullPolicy: IfNotPresent
            command: '/usr/local/bin/gphotos-cdp'
            args:
              - -v
              - -dev
              - -headless
              - -dldir
              - /download
              - -run
              - /mounted/save.sh
            envFrom:
              - configMapRef:
                  name: &config gphotos-config
            probes:
              liveness:
                custom: true
                spec:
                  exec:
                    command:
                      - cat
                      - /dest/healthy
              readiness:
                custom: true
                spec:
                  exec:
                    command:
                      - cat
                      - /dest/healthy
              startup:
                custom: true
                spec:
                  exec:
                    command:
                      - cat
                      - /dest/healthy

    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.172.90.43
        ports:
          http:
            port: 6901

    persistence:
      main:
        existingClaim: local-gphotos
        advancedMounts:
          main:
            main:
              - path: /dest
                subPath: photos_202105
              - path: /tmp/gphotos-cdp
                subPath: profile
              - path: /download
                subPath: tmp
              - path: /mounted
                subPath: scripts

