apiVersion: v1
kind: Secret
metadata:
    name: workload-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:S/Xtc8Nok3ZHatlm2+U4cjs=,iv:yWgja8Vkk1S3jXMyng76eBoiziXq6FQ5NG6zB0OzrWI=,tag:TAbSo0t7M+rIS5wHmRNqPg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:3z8uIp9YpcUxvw==,iv:fPSJpl35IXKVh04P3bhztoeDe6fxGs11sIaiNzyynQQ=,tag:sf0hrMtcu8HGx7vSYeT4Vw==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:JvH22zVw71eH9wq0CrW7U1fu/8T922XSXOWkOghjOuM73F0e+nc0EQ==,iv:UOEpOE8TB+WQhYIjoq3tFoLfm1bS96GC1fGI3QeyhDE=,tag:11tCp5UFH6TQ1PpSFSRbgQ==,type:str]
    IP_RANGE: ENC[AES256_GCM,data:Z8NNqaTSYsbVNkWhpjWOSQW2AnAwhDH/Yw==,iv:aUk2M9mqhM9SVa/rpOz7eTIT/4OQPOIVKnU7yW/M39g=,tag:mjDjNFnEgjAbByyYhc6C/A==,type:str]
    INGRESS_IP: ENC[AES256_GCM,data:bnSQwrBmLY6fYGQk,iv:pdxXYxIGP7r/8YsiNtCLWKGgCSxmZF0wrrM1iW/GR6k=,tag:ZAmGNhPc02Iuc8P1etGCZw==,type:str]
    INGRESS_HOST: ENC[AES256_GCM,data:+TZEWGFKjCTbZva4zsXzJnF80Q==,iv:eVuU5j3b9YWPEwW2CPajwG4k0uFHDiDU7/QK5jJlLto=,tag:avRbX+GmVtXiYO3Bg4rvUQ==,type:str]
    NAS_HOST: ENC[AES256_GCM,data:Nh43+0IT/XLmMos=,iv:6AZzkkRig2rvKFl2/kRMDBirqnzWQgzOoBddPbt4Akw=,tag:kZVK2Bln2NdO0UxZYm7VwQ==,type:str]
sops:
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeFExbkVSbDhTMkxjS0c3
            TVd2Q1lNZmFCdWswUDh5Z1I5ZTh4Z3FwMGpBCkdQOVBBM2lGZ2NPN29XUTBwSFlh
            ZlBycFFQbzRxaExnRVhNU3Y1MVJ0b1UKLS0tIFBCRUFWKytYZGVTSGIyeTBaNkZ0
            akRaUlpFL2lyZ0VGMkRiVnp5dS9DSGMKjBVdW9wqONDkaoortRsk7cY4XITIFHqw
            19Tj1wtpsk8BFxw0oMGb+XXgsVowVXKawow5YQsen4AbixuGSQwr8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T21:01:45Z"
    mac: ENC[AES256_GCM,data:4/ARP5wt6Pj4/8WKrGEqu7EcnmUo9qkfxl7epodMoAXE7bEOT4sy07Kc9g4Sk738Xn8Vyut2hBJqWkS15O3ez7/vMeIoodkOdAWRotJQLmDLZNVt8dUc6/wjUFwOUslsGAHqjbldY/a+slAxQ7x04zF7DjQxbpt2+CSB/yZ+93c=,iv:CiP6uhdf+vwKdMG2TndTw0uI/ZD4M/LlYaJCjWEI0mY=,tag:zLSgeVdXulD6s+DT1HVC4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
